package main

import (
	"log"
	"time"

	"river-api/internal/config"
	"river-api/internal/database"
	"river-api/internal/handlers"
	"river-api/internal/repository"
	"river-api/internal/routes"
	"river-api/internal/services"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"

	// Imported for its init() side effect: registers the generated swagger
	// spec under swag's global registry so gin-swagger can serve it. The
	// docs/ package is regenerated by `swag init` (see Makefile).
	_ "river-api/docs"
)

// @title           River API
// @version         1.0
// @description     REST API for the River self-hosted media platform.
// @description     Auth flow: POST /api/auth/login → use the returned
// @description     access_token as a Bearer token on the protected routes.
// @description     The stream_token is a longer-lived JWT restricted to
// @description     /stream and /download endpoints (the <video> element
// @description     can't send custom auth headers; it goes in the URL as
// @description     ?token=…).
//
// @host            localhost:8080
// @BasePath        /api
//
// @securityDefinitions.apikey BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Bearer JWT — paste "Bearer <token>" or use the Authorize button.
func main() {
	cfg := config.Load()

	db, err := database.Connect(cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}
	if err := database.Migrate(db); err != nil {
		log.Fatalf("failed to run migrations: %v", err)
	}

	// Repositories
	userRepo          := repository.NewUserRepository(db)
	refreshTokenRepo  := repository.NewRefreshTokenRepository(db)
	libraryRepo       := repository.NewLibraryRepository(db)
	movieRepo         := repository.NewMovieRepository(db)
	tvShowRepo        := repository.NewTVShowRepository(db)
	seasonRepo        := repository.NewSeasonRepository(db)
	episodeRepo       := repository.NewEpisodeRepository(db)
	artistRepo        := repository.NewArtistRepository(db)
	albumRepo         := repository.NewAlbumRepository(db)
	trackRepo         := repository.NewTrackRepository(db)
	audiobookRepo     := repository.NewAudiobookRepository(db)
	chapterRepo       := repository.NewChapterRepository(db)
	progressRepo      := repository.NewProgressRepository(db)
	creditsRepo       := repository.NewCreditsRepository(db)
	subtitleRepo      := repository.NewSubtitleRepository(db)
	audioTrackRepo    := repository.NewAudioTrackRepository(db)
	collectionRepo    := repository.NewCollectionRepository(db)
	watchlistRepo     := repository.NewWatchlistRepository(db)
	watchPartyRepo    := repository.NewWatchPartyRepository(db)
	dismissedNextRepo := repository.NewDismissedNextUpRepository(db)
	serviceLogRepo    := repository.NewServiceLogRepository(db)
	mediaCleanupRepo  := repository.NewMediaCleanupRepository(db)

	// Services
	authSvc      := services.NewAuthService(userRepo, refreshTokenRepo, cfg.JWTSecret, cfg.JWTAccessExpiry, cfg.JWTRefreshExpiry, cfg.JWTStreamExpiry)
	librarySvc   := services.NewLibraryService(libraryRepo)
	movieSvc     := services.NewMovieService(movieRepo, mediaCleanupRepo)
	tvShowSvc    := services.NewTVShowService(tvShowRepo, seasonRepo, episodeRepo, mediaCleanupRepo)
	musicSvc     := services.NewMusicService(artistRepo, albumRepo, trackRepo)
	audiobookSvc := services.NewAudiobookService(audiobookRepo, chapterRepo, mediaCleanupRepo)
	progressSvc  := services.NewProgressService(progressRepo, movieRepo, episodeRepo, seasonRepo, tvShowRepo, userRepo, audiobookRepo, chapterRepo, dismissedNextRepo)
	creditsSvc   := services.NewCreditsService(creditsRepo)
	subtitleSvc      := services.NewSubtitleService(subtitleRepo)
	audioTrackSvc    := services.NewAudioTrackService(audioTrackRepo)
	collectionSvc    := services.NewCollectionService(collectionRepo, movieRepo, tvShowRepo, audiobookRepo)
	watchlistSvc     := services.NewWatchlistService(watchlistRepo, movieRepo, tvShowRepo, audiobookRepo)
	watchPartySvc    := services.NewWatchPartyService(watchPartyRepo)
	serviceLogSvc    := services.NewServiceLogService(serviceLogRepo)
	searchRepo   := repository.NewSearchRepository(db)
	searchSvc    := services.NewSearchService(searchRepo)
	statsRepo    := repository.NewStatsRepository(db)

	// Handlers
	watchPartyHub := handlers.NewWatchPartyHub()

	r := gin.Default()

	// CORS — registered before any route so the preflight OPTIONS hits
	// the middleware first. The single literal "*" in the origin list
	// is the wildcard mode (browsers reject "*" + credentials, but we
	// authenticate via the Authorization header rather than cookies so
	// AllowCredentials stays off and "*" is safe). X-Total-Count is
	// exposed because the paged-list handlers put the row count there
	// and the JS clients read it for pagination.
	corsCfg := cors.Config{
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization", "X-Requested-With", "Accept"},
		ExposeHeaders:    []string{"Content-Length", "X-Total-Count"},
		AllowCredentials: false,
		MaxAge:           12 * time.Hour,
	}
	if len(cfg.CORSAllowedOrigins) == 1 && cfg.CORSAllowedOrigins[0] == "*" {
		corsCfg.AllowAllOrigins = true
	} else {
		corsCfg.AllowOrigins = cfg.CORSAllowedOrigins
	}
	r.Use(cors.New(corsCfg))

	routes.Register(r, cfg.JWTSecret,
		handlers.NewAuthHandler(authSvc),
		handlers.NewLibraryHandler(librarySvc),
		handlers.NewMovieHandler(movieSvc, cfg.RiverScanURL, cfg.MediaBasePath),
		handlers.NewTVShowHandler(tvShowSvc, cfg.RiverScanURL, cfg.MediaBasePath),
		handlers.NewMusicHandler(musicSvc),
		handlers.NewAudiobookHandler(audiobookSvc, cfg.RiverScanURL, cfg.MediaBasePath),
		handlers.NewAdminHandler(cfg.RiverScanURL, cfg.RiverMetaMovieURL, cfg.RiverMetaTVURL, cfg.RiverMetaBookURL, cfg.RiverMetaMusicURL, statsRepo, movieSvc, tvShowSvc),
		handlers.NewAdminUsersHandler(authSvc, progressSvc),
		handlers.NewUploadHandler(librarySvc, cfg.RiverScanURL),
		handlers.NewProgressHandler(progressSvc),
		handlers.NewProgressWSHandler(progressSvc),
		handlers.NewRecentlyAddedHandler(movieSvc, tvShowSvc),
		handlers.NewCreditsHandler(creditsSvc),
		handlers.NewSearchHandler(searchSvc),
		handlers.NewSubtitleHandler(subtitleSvc),
		handlers.NewAudioTrackHandler(audioTrackSvc),
		handlers.NewCollectionHandler(collectionSvc),
		handlers.NewWatchlistHandler(watchlistSvc),
		handlers.NewWatchPartyHandler(watchPartySvc, watchPartyHub),
		handlers.NewServiceLogHandler(serviceLogSvc),
		handlers.NewRequestHandler(cfg.RadarrURL, cfg.RadarrAPIKey, cfg.SonarrURL, cfg.SonarrAPIKey),
		handlers.NewImageProxyHandler(),
	)

	log.Printf("River API listening on :%s", cfg.Port)
	if err := r.Run(":" + cfg.Port); err != nil {
		log.Fatalf("server error: %v", err)
	}
}
